### ISSUE TITLE
webpack build fails on connection errors

### ISSUE THREAD

**Issue by boredland** [smooth-code/bundle-analyzer-javascript#11]
sometimes the bundle analyzer service fails, causing our CI to break. I would very much prefer if those errors got catched and logged instead of thrown. This plugin to run isn't a needed condition for the CI to pass...
```
Error: Bundle Analyzer - Request failed with status code 503
    at /home/runner/work/sputnik/sputnik/node_modules/@bundle-analyzer/webpack-plugin/lib/index.js:32:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
```

**Comment by gregberge** [comment]
Hello, I don't have time to maintain this project. Looking for a maintainer.
